name = "brocard"
version = "0.1.0"
defaultTargets = ["WilsonOffset"]
packagesDir = "../../../.lake/packages"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.32.0"

[[lean_lib]]
name = "FactorialMod151"

[[lean_lib]]
name = "FactorialPrimePower"

[[lean_lib]]
name = "WilsonOffset"
