name = "brocard_q1"
version = "0.1.0"
defaultTargets = ["FactorialMod151"]
packagesDir = "../../../.lake/packages"

[[require]]
name = "mathlib"
path = "../../../.lake/packages/mathlib"

[[lean_lib]]
name = "FactorialMod151"
